// Stamps the project root with a buildVersion.ts containing the current
// timestamp so the running page can show what build it's on.
//
// Lives at the project root (not under web/) so slift-watch's `web/*.ts` glob
// doesn't pick it up and trigger an infinite rebuild loop.

const fs = require("fs");
const path = require("path");

// Epoch ms — the browser formats it into local time with formatDateTime.
const ts = Date.now();
const contents = `// Auto-generated by scripts/writeBuildVersion.js. Do not edit.
export const BUILD_TIMESTAMP = ${ts};
`;
const out = path.resolve(__dirname, "..", "buildVersion.ts");
fs.writeFileSync(out, contents);
console.log(`[version] wrote ${path.basename(out)} = ${ts}`);
